language: java
sudo: false

jdk:
  - oraclejdk8
  - openjdk7

install: true
script: ./travis.sh

env:
  - TESTS=CI
  - TESTS=IT-DEV

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
