language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh

env:
  matrix:
    - TARGET=CI
    - TARGET=IT SQ_VERSION=DEV
    - TARGET=IT SQ_VERSION=5.1.2
    - TARGET=IT SQ_VERSION=LTS

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
