language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh

env:
  matrix:
    - PR_ANALYSIS=true
    - RUN_ITS=true SQ_VERSION=DEV
    - RUN_ITS=true SQ_VERSION=5.1.2
    - RUN_ITS=true SQ_VERSION=LTS

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
