language: java

jdk:
  - oraclejdk8
  - openjdk7

script: mvn clean verify

install: true

# Container-based infrastructure
sudo: false

# Keep Maven local repository between builds
cache:
  directories:
    - '$HOME/.m2/repository'
